### ISSUE TITLE
Loging out/deleting session.

### ISSUE THREAD

**Issue by knobo** [fukamachi/lack#10]
Is this how session objects are indented to be handled?
Like this "logout" middleware:

``` lisp
(lambda (app)
   (lambda (env)
     (let ((path-info (getf env :path-info)))
       (when (string-equal "/logout" path-info)
         (setf (getf (getf env :lack.session.options) :expire) t))
       (funcall app env))))
```

**Comment by ghost** [comment]
Hello @knobo 

We are developing a web application module library atop of caveman and were wondering if we are allowed to use this code there as means to provide a logout mechanism as a part of the user management modules. The library will be open source.

On what terms would you be willing to allow the use of this code?

**Comment by knobo** [comment]
You can do it, but it's better to do just.

``` cl
(defroute ("/logout" :method :get) ()
  (clrhash *session*)
  (redirect "/so-long-and-thanx-for-all-the-fish"))

```

If you don't whan't to do that, you can use my code under any of this licenses:
WTFPL (version 1 or 2), CC0, CDDL,

**Comment by ghost** [comment]
Thank you for allowing us to use this. I was so fixated on trying to expire the session that I didn't even consider such a simple solution. Naturally there needn't be a call to expiring a session if there is no data in it as long as the session cookie is set to expire at some reasonable time.

If you want, I can give you a link to the beginnings of the library as soon as we get it public.
