### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by rlisper** [fukamachi/lack#22]
CL-USER> (ql:quickload :lack)
To load "lack":
  Load 1 ASDF system:
    lack
; Loading "lack"
[package lack.util]
; 
; caught ERROR:
;   READ error during COMPILE-FILE:
;  
;     The symbol "SYSTEM-NOT-FOUND" is not external in the QUICKLISP-CLIENT package.
;  
;       Line: 24, Column: 44, File-Position: 813
;  
;       Stream: #<SB-INT:FORM-TRACKING-STREAM
;                 for "file /Users/user/quicklisp/dists/quicklisp/software/lack-20160825-git/src/util.lisp"
;                 {1004835CA3}>

**Comment by fukamachi** [comment]
What version of Quicklisp are you using?

``` common-lisp
(ql:client-version)
;=> "2016-02-22"
```

The latest version is `"2016-02-22"`. Make sure if your Quicklisp client is up to date with `(ql:update-client)`.

**Comment by rlisper** [comment]
Updating from version 2012010700 to version 2016022200. Solved!
