### ISSUE TITLE
null content-type breaks request handling

### ISSUE THREAD

**Issue by fiddlerwoaroof** [fukamachi/lack#39]
If the Content-Type header isn't passed, this code passes a content-type of NIL to HTTP-BODY:PARSE, preventing the request from being processed properly.

https://github.com/fukamachi/lack/blob/8ddb6530070ac261560098c0a1841b787eee19ca/src/request.lisp#L105-L108

This could be fixed either by adding a null check or defaulting content-type to `text/plain` when it's not passed.

**Comment by fukamachi** [comment]
Content-Type is thought to be required in Clack as it’s written in Lack’s README.

> :content-type (Required, String)

Did you get this error with some Clack handler or situation?

**Comment by fiddlerwoaroof** [comment]
I'm writing a backend for this: http://www.todobackend.com/client/index.html?http://localhost:5000 and I've discovered that their DELETE requests don't set the Content-Type header: 

```DELETE /todo/46 HTTP/1.1.
Host: localhost:5000.
Connection: keep-alive.
Pragma: no-cache.
Cache-Control: no-cache.
Accept: application/json, text/javascript, */*; q=0.01.
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.19 Safari/537.36.
Sec-Fetch-Mode: cors.
Origin: http://www.todobackend.com.
Sec-Fetch-Site: cross-site.
Referer: http://www.todobackend.com/client/index.html?http://localhost:5000.
Accept-Encoding: gzip, deflate, br.
Accept-Language: en,fr;q=0.9,de;q=0.8,es;q=0.7,zh-TW;q=0.6,zh;q=0.5,ja;q=0.4,pt;q=0.3,pl;q=0.2,fr-FR;q=0.1,en-US;q=0.1,en-GB;q=0.1.
```

I'm just using a fairly simple ningle app: https://github.com/fiddlerwoaroof/cl-todo-backend/blob/master/routing.lisp#L33 using the Hunchentoot handler and something isn't being setup correctly.

**Comment by fukamachi** [comment]
I think the code only runs when `Content-Length` or `Transfer-Encoding: chunked` exist. Does the todobackend.com sends those headers without Content-Type with DELETE requests?
Sorry, I couldn't try your cl-todo-backend because of a data-lens package issue.

```
; caught ERROR:
;   READ error during COMPILE-FILE:
;
;     Symbol "MAKE-LIST-LENS" not found in the DATA-LENS.LENSES package.
;
;       Line: 4, Column: 49, File-Position: 134
;
;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /Users/fukamachi/Programs/etc/cl-todo-backend/lack-cors-middleware.lisp" {1001E99823}>
```

**Comment by fiddlerwoaroof** [comment]
Ah, yeah, the relevant changes to data-lens haven't made it up to quicklisp

**Comment by fukamachi** [comment]
This was caused because the latest Http-Body assumes `content-type` is a string and passes to `starts-with`.

https://github.com/fukamachi/http-body/commit/f7230c8c5348bf8e022cc6b1b95e35a1f18fdcaf#diff-a12cf9db7767789dad9bcd52d001cb46L14-R16
