### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [fukamachi/lack#59]
Building with SBCL 2.1.6 / ASDF 3.3.5 for quicklisp dist creation.

Trying to build commit id d9a7633661b7ad47e0f354f48ec7beb9592c6157

*t-lack* fails to build with the following error:

```
Unhandled ASDF/FIND-COMPONENT:MISSING-DEPENDENCY in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001BE8103}>: Component :CLACK-V1-COMPAT not found, required by #<SYSTEM "t-lack">

```

[Full log here](http://report.quicklisp.org/2021-07-18/failure-report/lack.html)

**Comment by fukamachi** [comment]
Thank you for reporting!
I deleted tests for clack-v1-compat at 58394156f9f765c55f6f61ad7a8bf4f6eeaa286b.
