### ISSUE TITLE
cl-isaac fails to load on Windows CCL

### ISSUE THREAD

**Issue by ro6** [fukamachi/lack#73]
It tries to access /dev/arandom to init the random seed, which doesn't exist on Windows.

![image](https://github.com/fukamachi/lack/assets/8773802/01d11b7a-6555-4e48-a3a3-73a48fd55f9b)

I'm new to CL, so not sure whether this is an issue with lack, cl-isaac, or CCL.

**Comment by ro6** [comment]
I guess it's because the `*features*` var on CCL indicates Windows differently:

```common-lisp
(:SWANK :QUICKLISP :ASDF3.3 .... :X86-64 :X86_64 :X86-TARGET :X86-HOST :X8664-TARGET :X8664-HOST :WINDOWS-HOST :WINDOWS-TARGET :WIN64-TARGET :WIN64-HOST :64-BIT-TARGET :64-BIT-HOST :WINDOWS :LITTLE-ENDIAN-TARGET :LITTLE-ENDIAN-HOST)
```

so maybe the feature guards like:
```common-lisp
#-(or mswindows win32 cormanlisp)
``` 
should be:
```common-lisp
#-(or windows mswindows win32 cormanlisp)
```

to cover CCL as well?

**Comment by fukamachi** [comment]
Thank you for reporting.

Yeah, you seem right!
But, cl-issac is removed for other reason (#74), so this issue will also be resolved.
