### ISSUE TITLE
`t-lack-session-store-dbi` is missed?

### ISSUE THREAD

**Issue by catap** [fukamachi/lack#80]
`t-lack-session-store-dbi` is used at `lack-session-store-dbi.asd` but never defined.

**Comment by khinsen** [comment]
There are many more test systems missing. The full list is:
- `t-lack-component`
- `t-lack-middleware-accesslog`
- `t-lack-middleware-auth-basic`
- `t-lack-middleware-backtrace`
- `t-lack-middleware-session`
- `t-lack-middleware-static`
- `t-lack-request`
- `t-lack-session-store-dbi`
- `t-lack-session-store-redis`
- `t-lack-util`

**Comment by fukamachi** [comment]
They are old systems that are removed when migrating to Rove.
