### ISSUE TITLE
lack/util won't load using quicklisp due to missing dependancy CL-ISAAC

### ISSUE THREAD

**Issue by argentcorvid** [fukamachi/lack#83]
using Windows and SBCL.

on trying to install fukamachi-lack-20240209100541 from ultralisp:

[package lack/util];
; caught ERROR:
;   READ error during COMPILE-FILE:
;
;     Package CL-ISAAC does not exist.
;
;       Line: 98, Column: 22, File-Position: 3853

installing ISAAC with quicklisp and retrying works.

**Comment by rabbibotton** [comment]
in the mean time (ql:quickload :cl-isaac) before loading lack. I use the workaround here https://github.com/rabbibotton/clog-win64-ez

**Comment by fukamachi** [comment]
Fixed by https://github.com/fukamachi/lack/commit/7e7c404736a89c10f1e1d4601f0fefae35e74cf7.
