### ISSUE TITLE
Same Issue as in  #84 still persists

### ISSUE THREAD

**Issue by nerap528** [fukamachi/lack#93]
The error described in issue #84 still persists on different systems.
`The value
  -1
is not of type
  (UNSIGNED-BYTE 64)
   [Condition of type TYPE-ERROR]

Restarts:
 0: [ABORT] abort thread (#<THREAD "hunchentoot-worker-127.0.0.1:35762" RUNNING {1003991ED3}>)

Backtrace:
  0: (CL-ISAAC:RAND64 #S(CL-ISAAC:ISAAC64-CTX :RANDCNT 0 :RANDRSL #(11765768399845579605 13599022206707435575 11164147462468693029 5479293572085768392 8816757518368503976 80$
      Locals:
        CTX = #S(CL-ISAAC:ISAAC64-CTX ..)
  1: (CL-ISAAC:RAND-BITS-64 #S(CL-ISAAC:ISAAC64-CTX :RANDCNT 0 :RANDRSL #(11765768399845579605 13599022206707435575 11164147462468693029 5479293572085768392 8816757518368503$
      Locals:
        CTX = #S(CL-ISAAC:ISAAC64-CTX ..)
        N = 160
  2: (LACK.UTIL:GENERATE-RANDOM-ID)
`

This example is from a **Ubuntu 24.04 LTS** server.
My current workaround is to quickload ironclad at the very top of the .asd file of any project that uses `lack-middleware-session` and removing all reader-conditionals from `#'lack.util:generate-random-id` in order to always use ironclad.

**Comment by fukamachi** [comment]
What version, or where did you get Lack from?
The issue was fixed in February, but Quicklisp has not released a new dist since last October.
I want to make sure you're using the latest version.

**Comment by nerap528** [comment]
Version 0.2.0 is used. 
I cloned the version 0.3.0 from git into a `third-party` directory inside my projects root and did a `(ql:register-local-projects)` for now.
I hope the quicklisp version is updated eventually.

Thanks for the reply.

**Comment by nerap528** [comment]
:)
